### ISSUE TITLE
Function names and haddock comments

### ISSUE THREAD

**Issue by dsorokin** [peddie/nlopt-haskell#1]
Hi Matthew,

I’m looking for an optimisation library for my simulation framework Aivika. Your library seems to be very interesting and promising. 

Have you plans to use a more Haskell idiomatic naming convention for functions and add haddock comments too?

For example, there are at least two choices. These new functions could be placed in completely another module, or they could be placed in the same module, but the old functions using the C-style naming function could be declared as deprecated.

I’m just very curios to know what plans do you have regarding this library.

Best regards,
David Sorokin

**Comment by peddie** [comment]
Hi David,

Somehow I never received an email notification about this.  I assume this is no longer relevant to you due to the elapsed time.

I do not have any plans to redo the naming scheme in this package.  It's intended to remain a low-level interface, so that any idiomatic Haskellization can happen in a separate package, according to people's differing opinions about what the appropriate Haskell interface to NLOPT looks like, without having to repeat the boring FFI work done here in `nlopt-haskell`.  I have provided one possible such idiomatic Haskell interface in my [hmatrix-nlopt](https://hackage.haskell.org/package/hmatrix-nlopt) package, which follows [hmatrix](https://hackage.haskell.org/package/hmatrix) API conventions.

I also don't have plans to provide haddock documentation for individual functions, since they merely call their C equivalents in NLOPT.  See [the comments in the main bindings file](https://github.com/peddie/nlopt-haskell/blob/master/src/Numeric/Optimization/NLOPT/Bindings.hs#L13) for links to the upstream documentations and pointers to the minor differences.

I apologize for the absurd delay on this!

**Comment by dsorokin** [comment]
Thanks Matt for the reply. No problem. I agree that the FFI functions should correspond to NLOPT.
